Repository toychip/paystub, pull requests merged in 2023-08, with the labels that each got.

#45 Feat: 추가 기능 구현 (#44)
  src/main/java/com/paystub/controller/AdminController.java
  src/main/java/com/paystub/controller/UserController.java
  src/main/java/com/paystub/repository/UserMapper.java
  src/main/java/com/paystub/service/UserService.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/admin.html
  src/main/resources/templates/adminUserForm.html
  src/main/resources/templates/user.html
  src/main/resources/templates/userSelect.html
Labels: Refactor, Feature, design, 유선우, BE, FE

#49 Feat error 페이지 및 페이징 수정
  src/main/java/com/paystub/config/MessageConfig.java
  src/main/java/com/paystub/config/SecurityConfig.java
  src/main/java/com/paystub/config/SuperAdminInit.java
  src/main/java/com/paystub/controller/AdminController.java
  src/main/java/com/paystub/controller/AuthController.java
  src/main/java/com/paystub/controller/UserController.java
  src/main/java/com/paystub/dto/UserDao.java
  src/main/java/com/paystub/repository/UserMapper.java
  src/main/java/com/paystub/service/AdminService.java
  src/main/resources/erros.properties
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/admin.html
  src/main/resources/templates/adminUserForm.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/userSelect.html
Labels: Refactor, Feature, 유선우, FE

#53 DEV: 로그인 실패처리
  src/main/java/com/paystub/admin/controller/AdminAccountController.java
  src/main/java/com/paystub/admin/controller/AdminExelController.java
  src/main/java/com/paystub/admin/dto/request/AdminSearchRequest.java
  src/main/java/com/paystub/admin/repository/AdminMapper.java
  src/main/java/com/paystub/admin/service/ExelService.java
  src/main/java/com/paystub/admin/service/ManagementUserService.java
  src/main/java/com/paystub/admin/service/SalaryService.java
  src/main/java/com/paystub/comon/controller/AuthController.java
  src/main/java/com/paystub/comon/securityconfig/CustomAuthenticationFailureHandler.java
  src/main/java/com/paystub/comon/securityconfig/CustomAuthenticationProvider.java
  src/main/java/com/paystub/comon/securityconfig/SecurityConfig.java
  src/main/java/com/paystub/user/controller/UserController.java
  src/main/java/com/paystub/user/service/UserService.java
  src/main/resources/templates/admin/adminSalary.html
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/user/userPaging.html
  src/main/resources/templates/user/userSalary.html
Labels: dev, 임준형, 유선우

#55 BREAKING CHANGE: database 변경
  build.gradle
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
Labels: BREAKING CHANGE, dev, 임준형, BE
